### ISSUE TITLE
`read error: 0: Resource temporarily unavailable` when querying user for branch name

### ISSUE THREAD

**Issue by rorybyrne** [benelan/gh-fzf#38]
https://github.com/benelan/gh-fzf/blob/510181caf1ecfb2547a1ef20924b6a1c05c0c427/gh-fzf#L866-L875

Line 873 produces the following error when I run `gh fzf i` and then `alt-o`. This happens on MacOS using Tabby terminal and zsh.

```
➜  my_project git:(main) gh fzf i                                                
Enter branch name for #9: /Users/rory/.local/share/gh/extensions/gh-fzf/gh-fzf: line 873: read: read error: 0: Resource temporarily unavailable
```

Versions:
```
➜  my_project git:(main) gh --version
gh version 2.53.0 (2024-07-17)
https://github.com/cli/cli/releases/tag/v2.53.0
➜  my_project git:(main) gh fzf --version
v0.14.0
➜  my_project git:(main) zsh --version
zsh 5.9 (arm64-apple-darwin24.0)
```

**Comment by benelan** [comment]
Thanks for the bug report! I can't reproduce on Ubuntu and Bash, but I'll try to investigate.

Does the error occur before the prompt is displayed or after you enter a branch name and press `enter`? Also, which version of `fzf` do you have installed?

**Comment by benelan** [comment]
It looks like fzf versions prior to [`0.53.0`](https://github.com/junegunn/fzf/releases/tag/0.53.0) required manual `/dev/tty` redirection when interactive programs are used in execute actions. If your fzf version is less than `0.53.0`, can you try the fix on `benelan/38-read-error` and let me know if it resolves your error? Thanks!

```sh
curl https://raw.githubusercontent.com/benelan/gh-fzf/benelan/38-read-error/gh-fzf > ~/.local/share/gh/extensions/gh-fzf/gh-fzf
```

**Comment by rorybyrne** [comment]
@benelan that worked - thank you! For context, the error was after pressing `option-o` (MacOS).

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/73c16fea-fe43-46ef-9f33-6f95307ffaaf">

**Comment by rorybyrne** [comment]
Also my fzf is at `0.54.3`.

**Comment by benelan** [comment]
> Also my fzf is at `0.54.3`.

Interesting, it must be something related to `zsh` or Mac then. I fixed all of the issues related to `read`, but there may be other tty problems that I don't reproduce on my end either. If you find one, please log another issue and I'll get it fixed. Thanks again for the report!
